mutation UpdateLoan($id: ID!, $changes: LoanUpdateInput!) {
  updateLoan(where: { id: $id }, data: $changes) {
    id
    loanAmount
    name
    payments(orderBy: date_DESC) {
      date
      id
      interest
      note
      principal
    }
    periodInterestRate
    periods
    periodType
    startDate
  }
}
