name: Checks

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: public

      - name: Run Parcel build
        run: parcel build ./src/index.html --out-dir ./public --no-autoinstall

      - name: Publish static content
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
