name: Production CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Restore dependencies
        run: yarn install --frozen-lockfile

      - name: Run Snowpack build
        run: yarn build
        env:
          SNOWPACK_PUBLIC_SENTRY_DSN: https://f911c31ea80e475bb301cab5e2e59693@o291540.ingest.sentry.io/1533229
          SNOWPACK_PUBLIC_SENTRY_ENVIRONMENT: production

      # No need to publish artifact for now. GitHub free storage is pretty limited
      # - name: Publish static content
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: site
      #     path: public

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          channelId: live
