name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Restore dependencies
        run: yarn install --frozen-lockfile

      - name: Run Parcel build
        run: parcel build ./src/index.html --out-dir ./public --no-autoinstall
        env:
          SENTRY_DSN: https://f911c31ea80e475bb301cab5e2e59693@o291540.ingest.sentry.io/1533229
          SENTRY_ENVIRONMENT: production

      # No need to publish artifact for now. GitHub free storage is pretty limited
      # - name: Publish static content
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: site
      #     path: public

      - name: Deploy to Firebase
        if: github.ref == 'refs/heads/master'
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
